name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install Flutter via subosito/flutter-action with a stable version that works
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.12.0'
          channel: stable

      # Enable flutter web
      - run: flutter config --enable-web

      # Get dependencies
      - run: flutter pub get

      # Build the Flutter web app
      - run: flutter build web --release

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
