name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Flutter (latest stable with Dart 3.9+)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.10'
          channel: stable

      # 3. Print Flutter & Dart versions (optional, for debugging)
      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Build Flutter web
      - name: Build Flutter web
        run: flutter build web --release --base-href /boat_finance_web/

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
