name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # Or the version you're using

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release --base-href /boat_finance_web/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
